apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "prmoji.fullname" . }}
  labels:
    {{- include "prmoji.labels" . | nindent 4 }}
data:
  PORT: {{ .Values.config.port | quote }}
  LOG_LEVEL: {{ .Values.config.logLevel | quote }}
  RETENTION_DAYS: {{ .Values.config.retentionDays | quote }}
  DB_PATH: {{ printf "%s/prmoji.db" .Values.persistence.mountPath | quote }}
  IGNORED_COMMENTERS: {{ .Values.config.ignoredCommenters | quote }}
