{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "prmoji.serviceAccountName" . }}
  labels:
    {{- include "prmoji.labels" . | nindent 4 }}
{{- end }}
